"""Deterministic generation from data/*.json. Use --check in CI."""
from __future__ import annotations
import argparse
import json
from collections import Counter
from pathlib import Path
from catalog import ROOT, load, validate, bibtex, csv_text, doi_url

def md(p: dict) -> str:
    author='; '.join(p['authors'])+(' et al. (author metadata incomplete)' if not p['authors_complete'] else '')
    links=[f"[Primary source]({p['url']})"]
    if p['doi']:links.append(f"[DOI]({doi_url(p['doi'])})")
    if p['arxiv']:links.append(f"[arXiv](https://arxiv.org/abs/{p['arxiv']})")
    if p['code_url']:links.append(f"[Author-linked code]({p['code_url']})")
    links.extend(f'[Evidence {i+1}]({u})' for i,u in enumerate(p['sources']) if u!=p['url'])
    if p['record_type']=='bibliographic':
        return f'''<a id="{p['id']}"></a>
### {p['year']} · {p['title']}

{author} · *{p['venue']}* · **{p['publication_status']}** · `{p['scope']}` · `bibliographic`

书目与主题已核对；方法、输入、时间窗及结果待阅读原文。Bibliographic record; detailed study annotation pending.

{p['caveat']}

{' · '.join(links)}

Code availability: {'author-linked release above' if p['code_url'] else 'not verified in this snapshot'}.
'''
    return f'''<a id="{p['id']}"></a>
### {p['year']} · {p['title']}

{author} · *{p['venue']}* · **{p['publication_status']}** · `{p['scope']}` · `annotated`

{p['summary']}

{p['summary_zh']}

- **Method / input:** {p['method']} / {p['inputs']}.
- **Target & horizon:** {p['target_and_horizon']}.
- **Reading caution:** {p['caveat']}
- **Provenance:** {p['verification']['level']} checked {p['verification']['checked_on']}; independently reproduced: {str(p['verification']['reproduced']).lower()}.

{' · '.join(links)}

Code availability: {'author-linked release above' if p['code_url'] else 'not verified in this snapshot'}.
'''

def outputs(root: Path = ROOT) -> dict[str,str]:
    papers,categories,config,routes=load(root)
    errors=validate(papers,categories,config,routes)
    if errors:raise ValueError('\n'.join(errors))
    ordered=sorted(papers,key=lambda p:(-p['year'],p['title'].casefold()))
    counts=Counter(p['category'] for p in papers)
    scopes=Counter(p['scope'] for p in papers)
    detail=Counter(p['record_type'] for p in papers)
    payload={'config':config,'categories':categories,'routes':routes,'papers':[dict(p,bibtex=bibtex(p)) for p in ordered]}
    out={'docs/catalog.js':'// Generated by tools/build.py; edit data/*.json instead.\nwindow.TORNADO_CATALOG = '+json.dumps(payload,ensure_ascii=False,indent=2).replace('</','<\\/')+';\n',
         'papers/references.bib':'% Generated bibliography. Partial author records explicitly use "and others".\n% Check publisher metadata before submitting a manuscript.\n\n'+'\n'.join(bibtex(p) for p in ordered),
         'papers/catalog.csv':csv_text(ordered)}
    toc='\n'.join(f"- [{c['number']} · {c['name']} ({counts[c['id']]})]({c['id']}.md)" for c in categories)
    sections=[]
    for c in categories:
        subset=[p for p in ordered if p['category']==c['id']]
        body=f"# {c['name']}\n\n{c['name_zh']} · {len(subset)} records · snapshot {config['snapshot_date']}\n\n[Back to the catalog](README.md) · [Scope and evaluation](../guides/TASKS.md)\n\n"+'\n---\n\n'.join(md(p) for p in subset)
        out[f"papers/{c['id']}.md"]=body
        sections.append(f"## {c['number']} · {c['name']}\n\n"+'\n---\n\n'.join(md(p) for p in subset))
    out['papers/README.md']=f"# The literature atlas\n\n{len(papers)} source-linked records; {config['snapshot_date']}. {detail['annotated']} annotated entries and {detail['bibliographic']} bibliographic entries awaiting detailed reading. Inclusion does not imply endorsement or reproduction.\n\n`direct`: tornado-specific. `context`: severe-storm or operational context. `transfer`: potentially useful weather AI, not tornado validation.\n\n[Full catalog](ALL_PAPERS.md) · [Code index](CODE_INDEX.md) · [BibTeX](references.bib) · [CSV](catalog.csv)\n\n{toc}\n"
    out['papers/ALL_PAPERS.md']='# Awesome Tornado AI — source-linked catalog\n\nGenerated from `data/papers.json`. Entries distinguish method annotations from bibliography-only indexing. This is not an exhaustive systematic review. No full paper abstracts are reproduced.\n\n'+'\n---\n\n'.join(sections)
    code_papers=[p for p in ordered if p['code_url']]
    code_rows=[]
    for p in code_papers:
        label='GitHub' if 'github.com/' in p['code_url'] else 'Code archive'
        title=p['title'].replace('|','\\|')
        code_rows.append(f"| {p['year']} | [{title}]({p['url']}) | [{label}]({p['code_url']}) | [Scope / release notes]({p['category']}.md#{p['id']}) |")
    out['papers/CODE_INDEX.md']=f"# Paper and code links / 论文与代码\n\n{len(code_papers)} author- or institution-linked code releases, checked in this dated collection. A repository may offer inference only; follow each entry's release notes and the original README. Presence here does not certify training reproducibility or scientific performance. Missing entries mean code has not been verified here, not that it does not exist.\n\n| Year | Paper / primary source | Code | Catalog notes |\n|---|---|---|---|\n"+'\n'.join(code_rows)+'\n'
    table_en='\n'.join(f"| {c['number']} | [{c['name']}](papers/{c['id']}.md) | {counts[c['id']]} |" for c in categories)
    table_zh='\n'.join(f"| {c['number']} | [{c['name_zh']}](papers/{c['id']}.md) | {counts[c['id']]} |" for c in categories)
    route_lines=[]
    byid={p['id']:p for p in papers}
    for r in routes:
        route_lines.append(f"### {r['level']} · {r['name']} / {r['name_zh']}\n\n{r['description']} {r['description_zh']}\n\n"+'\n'.join(f"{i+1}. [{byid[k]['year']} — {byid[k]['title']}](../papers/{byid[k]['category']}.md#{k})" for i,k in enumerate(r['papers'])))
    out['guides/READING_ROUTES.md']='# Three routes into the storm\n\nRoutes are editorial suggestions, not quality rankings. Read primary papers and inspect data availability before implementing.\n\n'+'\n\n'.join(route_lines)+'\n\n**Do not skip the timestamp audit.** A convincing model can still learn from observations unavailable at its claimed forecast issue time.\n'
    replacements={'COUNT':str(len(papers)),'CATEGORY_COUNT':str(len(categories)),'DATE':config['snapshot_date'],'START_YEAR':str(min(p['year'] for p in papers)),'END_YEAR':str(max(p['year'] for p in papers)),'DIRECT_COUNT':str(scopes['direct']),'CONTEXT_COUNT':str(scopes['context']),'TRANSFER_COUNT':str(scopes['transfer']),'CATEGORY_TABLE_EN':table_en,'CATEGORY_TABLE_ZH':table_zh}
    replacements.update({'ANNOTATED_COUNT':str(detail['annotated']),'BIBLIOGRAPHIC_COUNT':str(detail['bibliographic']),'CODE_COUNT':str(sum(bool(p['code_url']) for p in papers)),'ADDED_COUNT':str(len(papers)-67),'WEBSITE_URL':config['website_url']})
    for name in ['README.md','README.zh-CN.md']:
        text=(root/'templates'/name).read_text(encoding='utf-8')
        for key,value in replacements.items():text=text.replace('{{'+key+'}}',value)
        out[name]=text
    out['data/stats.json']=json.dumps({'records':len(papers),'categories':len(categories),'by_scope':dict(sorted(scopes.items())),'by_category':dict(sorted(counts.items())),'by_record_type':dict(sorted(detail.items())),'code_links':sum(bool(p['code_url']) for p in papers),'snapshot':config['snapshot_date']},indent=2,ensure_ascii=False)+'\n'
    # Keep one canonical SVG; inline it so motion controls work offline and over HTTP.
    page=(root/'templates/index.html').read_text(encoding='utf-8')
    out['docs/index.html']=page.replace('{{STORM_SVG}}',(root/'docs/storm.svg').read_text(encoding='utf-8').strip())
    return {k:v.rstrip()+'\n' for k,v in out.items()}

def main() -> int:
    ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--check',action='store_true');args=ap.parse_args()
    try:generated=outputs()
    except (OSError,ValueError,KeyError,TypeError) as exc:
        print(f'Build failed: {exc}');return 1
    stale=[]
    for name,text in generated.items():
        path=ROOT/name
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8')!=text:stale.append(name)
        else:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(text,encoding='utf-8',newline='\n')
    if stale:print('Regenerate with python tools/build.py:\n'+'\n'.join(stale));return 1
    print(f'{"Checked" if args.check else "Generated"} {len(generated)} deterministic files.');return 0
if __name__=='__main__':raise SystemExit(main())
